### ISSUE TITLE
[Support] Slash commands, invalid permissions

### ISSUE THREAD

**Issue by OoLunar** [AustinTi/HolidayBot#5] opened 2022-04-13 18:48 UTC
Hello there! I struggled quite a bit trying to find a way to get support. I couldn't find a support server, the bot stopped responding to my messages (likely due to transitioning over to slash commands) and the invite link over at top.gg doesn't have the application command scope. It'd be nice if you could edit the bot description saying "Switched to slash commands, re-invite bot for functionality" or attempt to send a notice message to the server's community updates channel. All mild complaints, nothing to throw a fit about.

---

I'm attempting to re-setup the holiday bot however I'm encountering permission issues. Using `/set dailychannel channel: #holidays-of-the-early-dawn` (channel id `926478233497645086`), the bot claims to not have permissions for the channel, as shown:
![image](https://user-images.githubusercontent.com/46751150/163248312-330a1503-f37b-438f-b034-421feda30b97.png)
However, after utilizing channel overwrites, the bot certainly *should*  have permissions, as shown below:
![image](https://user-images.githubusercontent.com/46751150/163248443-eeb49672-009b-435a-aa87-4214f8c51fe3.png)
I even made sure to give the bot's role the requested permissions:
![image](https://user-images.githubusercontent.com/46751150/163248753-671ced6d-1b77-4980-a464-07a948aa6c14.png)
Just for testing, I gave the holiday bot role the admin permission, however that failed as well:
![image](https://user-images.githubusercontent.com/46751150/163249049-8ccb2545-9426-4aa8-86d0-f74ab2378f53.png)
A final screenshot of the roles that the bot has:
![image](https://user-images.githubusercontent.com/46751150/163249139-0351c60e-c181-4126-8896-521370af6bde.png)

---
Server id: `832354798153236510`
Daily Channel id: `926478233497645086`
Server bot role id: `832356525770276864`
Holiday managed role id: `963866781787783191`

If there's any other information you require, please don't hesitate to ask.

**Comment by barkloaf** [comment] 2022-04-27 07:46
sorry I didn't get to this sooner, apparently github does not put new issues in your own repos on your homepage. I've changed my watching settings so hopefully that fixes it?

anyway, there's a support server listed on top.gg, and the actual invite link on top.gg is correct, but the link contained in the "Invite" image for the description is not and I should probably change that soon

this seems to be a bit different than #4 according to logs that I can see, but similarly to #4, I cannot reproduce the issue so I don't think it affects most users. I will be a bit busy for a little bit and might not be able to get to this for a little while. I'm mostly just making this reply for now to let you know that I've seen this!

**Comment by barkloaf** [comment] 2022-05-28 20:54
hey, if you're still having this issue, I'd suggest joining the support server linked on top.gg. would make it easier to debug

**Comment by barkloaf** [comment] 2024-07-18 20:42
closing due to age. if this is still a problem please reply and I can open this again.

**Closed as not planned by barkloaf** 2024-07-18 20:42 UTC
